### ISSUE TITLE
24fps bug solution

### ISSUE THREAD

**Issue by knerlington** [simonedibilio/dhewm3#1]
I've found that com_preciseTic set to 0 fixes the 24fps bug.  Just tried with it set to 1 as usual and pretty soon I saw the framerate tank to 24fps, but changing the above in realtime immediately restores the framerate. You can even toggle it going back and forth between 24fps and in my case 165fps. So having it in the autoexec config is a good idea it seems.

**Comment by simonedibilio** [comment]
oh, that explains why with my config I wasn't getting the issue!! thank you for letting me know! cheers! :)
